### ISSUE TITLE
Enrichment works with IntelliJ but not on command line

### ISSUE THREAD

**Issue by x389liu** [dstlry/dstlr#27]
`EnrichTriples` works well in IntelliJ IDEA, but causes `java.lang.NullPointerException` when running on command line.

**Comment by talentoscope** [comment]
Also affects me.
Relevant output

`19/12/19 17:00:43 ERROR Executor: Exception in task 102.0 in stage 6.0 (TID 201)
java.lang.NullPointerException
        at org.apache.jena.query.ARQ.isTrue(ARQ.java:650)
        at org.apache.jena.sparql.lang.ParserBase.<init>(ParserBase.java:292)
        at org.apache.jena.sparql.lang.SPARQLParserBase.<init>(SPARQLParserBase.java:43)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11Base.<init>(SPARQLParser11Base.java:22)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.<init>(SPARQLParser11.java:4974)
        at org.apache.jena.sparql.lang.ParserSPARQL11.perform(ParserSPARQL11.java:91)
        at org.apache.jena.sparql.lang.ParserSPARQL11.parse$(ParserSPARQL11.java:52)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:52)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:40)
        at org.apache.jena.rdfconnection.RDFConnectionRemote.queryExec(RDFConnectionRemote.java:160)
        at org.apache.jena.rdfconnection.RDFConnectionRemote.query(RDFConnectionRemote.java:145)
        at org.apache.jena.rdfconnection.RDFConnection.lambda$querySelect$2(RDFConnection.java:125)
        at org.apache.jena.system.Txn.exec(Txn.java:79)
        at org.apache.jena.system.Txn.executeRead(Txn.java:117)
        at org.apache.jena.rdfconnection.RDFConnection.querySelect(RDFConnection.java:124)
        at io.dstlr.EnrichTriples$.getWikidataId(EnrichTriples.scala:108)
        at io.dstlr.EnrichTriples$$anonfun$4.apply(EnrichTriples.scala:53)
        at io.dstlr.EnrichTriples$$anonfun$4.apply(EnrichTriples.scala:53)
        at org.apache.spark.sql.execution.MapElementsExec$$anonfun$7$$anonfun$apply$1.apply(objects.scala:236)
        at org.apache.spark.sql.execution.MapElementsExec$$anonfun$7$$anonfun$apply$1.apply(objects.scala:236)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage4.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:232)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by talentoscope** [comment]
Looks like it's something to do with the query here

`    try {
      connection = RDFConnectionFactory.connect(sparqlEndpoint)
      connection.querySelect(s"SELECT ?object WHERE { ${encodedEntity} <http://schema.org/about> ?object }", new Consumer[QuerySolution] {
        override def accept(t: QuerySolution): Unit = {
          id = t.getResource("object").getURI()
        }
      })
    }`

**Comment by talentoscope** [comment]
Adding 

`org.apache.jena.query.ARQ.init()`

just before the try around line 106 in /dstlr/src/main/scala/io/dstlr/EnrichTriples.scala and rebuilding with 

`sbt assembly` 

fixed this error. Looks like ARQ does not get initialised in the scala code.

**Comment by r-clancy** [comment]
@x389liu are you able to replicate the `NullPointerException`? I just tried on my laptop (without the associated PR, just the normal `master` branch) in Intellij and I'm unable to replicate.

**Comment by talentoscope** [comment]
That's what OP said, it's not replicable in IntelliJ, but it is in a terminal ;)

**Comment by r-clancy** [comment]
> That's what OP said, it's not replicable in IntelliJ, but it is in a terminal ;)

I read it backwards. Just tested, looks good - going to merge now. Thanks!

**Comment by talentoscope** [comment]
Haha :)
No worries, happy to help!
